Sync annotations to google drive after exiting
MiraPurkrabek/PoseAnnotator pull request #3
Opened 2024-07-07 00:10 UTC by Fizza-Rubab

### What?
I have added functionality for uploading the annotations to Google Drive of the user. The annotations are uploaded only once after the user exits the program.
### Why?
A backup of the annotations can be stored in case the file on the local system gets corrupted. It can also be used by collaborators and supervisors to track progress on data annotation task.
### How?
Syncing to Google Drive uses the Google Drive API via the Pydrive wrapper. The user first has to setup the Google Drive API access through the Google Cloud Console (details mentioned in annotations.md in the docs). Once API and credentials are configured, the user can provide a flag in the script to enable syncing. The user can also provide a cloud folder id if they want the results to be saved in a specific folder.

2024-07-08 15:13 UTC, MiraPurkrabek requested changes
Hi @Fizza-Rubab ,
Thank you for the nice code. I tried the new feature and have several comments. Some might require code changes, while others are just curious questions.

1. How will we handle the sharing of user secrets when pushing to the repository? Having one JSON in the workdir and taking care not to accidentally upload it to GitHub seems too risky. I would propose adding the secrets.json (or maybe all JSONs) to .gitignore.
2. The current solution requires GDrive authentication after every app run. Would it be possible to authenticate the app just once and have Google remember the decision for at least some time?

2024-07-08 15:13 UTC, MiraPurkrabek commented on annotate_bboxes.py
> +from pydrive.drive import GoogleDrive
Consider making this import optional to allow the code running without PyDrive. I would opt for dynamic import only when args.cloud_upload is True but other options (like try/except etc.) are also possible.

2024-07-08 15:16 UTC, MiraPurkrabek commented
Once the above-mentioned issues/questions are resolved, I propose to:

1. Add PyDrive as an optional requirement to both the .txt and Conda env files.
2. Change "Miroslav Purkrabek" to "PoseAnnotator contributors" in the BibTeX citation, as I will no longer be the sole contributor.

2024-07-08 20:17 UTC, Fizza-Rubab commented
Hi @MiraPurkrabek, thank you for reviewing the code. 

1. I agree that the secrets file can be accidentally uploaded. It may be safer to add all *.json files to gitignore.
2. Thank you for pointing this out. Yes, it would be possible. I can save the access and refresh tokens in a file when the user authenticates the first time. They can then be loaded to prevent the authentication prompt from appearing until the file is deleted, or access is revoked.

I will share the updated code soon.

2024-07-10 06:22 UTC, MiraPurkrabek approved these changes

2024-07-10 06:23 UTC, merged

2024-07-10 06:27 UTC, MiraPurkrabek commented
All checks completed, merging into the main.
Thank you @Fizza-Rubab for the new feature.